on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '!**.md'
  pull_request:
    paths:
      - '**.py'
      - '!**.md'

jobs:
  python-tester:
    name: Pytest Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '>=3.12 <3.14'
      - name: Requirement installation
        run: pip install -r requirements.txt
      - name: Pytest running
        run: pytest